spring:
  application:
    name: gateway-web
  redis:
    host: 192.168.15.111
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowedOrigins: "*"#跨域处理允许所有的域
            allowedMethods: #支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: easymarket_goods_route
          uri: lb://SELLERSGOODS
          predicates:
            - Path=/api/brand/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流名字不能随便写，使用默认的facatory
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 4
        - id: easymarket_user_routes
          uri: lb://USER
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
        - id: easymarket_order_routes
          uri: lb://ORDER
          predicates:
            - Path=/api/cart/**,/api/order/**,/api/orderItem/**
          filters:
            - StripPrefix=1
#Redis配置
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
  web:
    exposure:
      include: true