server:
  port: 9007
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.15.111:3360/easymarket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    minIdle: 5 #最小连接池数量
    maxActive: 20 #最大连接池数量
    maxWait: 6000 #获取连接最大等待时间
  redis:
    host: 192.168.15.111
    port: 6379
  rabbitmq:
    host: 192.168.15.111
    port: 5672
    password: guest
    username: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰式编写规范
  type-aliases-package: com.ccw.user.pojo
# 配置sql打印日志
logging:
  level:
    com:
      offcn: debug